### ISSUE TITLE
Expose the hooks

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/cs-web-lib#68]
As a developer of GUIs for experimental use I'd like to make use of the communication utilities in cs-web-lib for my own widgets and components, so I would like hooks like `useDevice`, `useConnection` etc. to be exported

**Comment by abigailalexander** [comment]
HI @dperl-dls, sorry I missed this issue before. I think it's fine to export the hooks. It's worth noting this project is still in development so there's a possibility that we tweak some behaviour in future as needed, which might mean updating your own widgets and components too. 
If you're happy to do the work, that would be much appreciated

**Comment by dperl-dls** [comment]
Sure, we're used to that, it's still better than having to replicate all of that stuff :)
